server:
  port: 8888
spring:
  application:
    name: user-center
order-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8881,localhost:8882
    ServerListRefreshInterval: 15000