spring:
  application:
    name: order-service
  profiles:
    active: client1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: client1
server:
  port: 8881

---

spring:
  profiles: client2
server:
  port: 8882